import type { ChicagoEvent } from "@/types";

function dateAtOffset(daysFromNow: number, hour: number, minute = 0) {
  const d = new Date();
  d.setDate(d.getDate() + daysFromNow);
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
}

const EVENTS: ChicagoEvent[] = [
  {
    id: "millennium-concert",
    title: "Millennium Park Summer Music Series",
    description: "Outdoor evening concert at Pritzker Pavilion.",
    category: "music",
    costType: "free",
    costLabel: "Free",
    neighborhood: "The Loop",
    location: "Jay Pritzker Pavilion, Millennium Park",
    startAt: dateAtOffset(2, 18, 30),
    endAt: dateAtOffset(2, 20, 30),
    link: "https://www.chicago.gov/city/en/depts/dca/supp_info/millennium_park9.html",
  },
  {
    id: "lakefront-fun-run",
    title: "Lakefront Sunset Fun Run",
    description: "Community 5K run/walk with meet-up pace groups.",
    category: "fitness",
    costType: "free",
    costLabel: "Free",
    neighborhood: "Near Loop",
    location: "Lakefront Trail (Monroe Harbor start)",
    startAt: dateAtOffset(3, 18, 0),
    endAt: dateAtOffset(3, 19, 15),
    link: "https://www.chicagoparkdistrict.com/parks-facilities/lakefront-trail",
  },
  {
    id: "daley-plaza-market",
    title: "Daley Plaza Farmers Market",
    description: "Fresh produce, breads, and local vendors in the Loop.",
    category: "market",
    costType: "free",
    costLabel: "Free entry",
    neighborhood: "The Loop",
    location: "Daley Plaza",
    startAt: dateAtOffset(4, 8, 0),
    endAt: dateAtOffset(4, 14, 0),
    link: "https://www.chicago.gov/city/en/depts/dca/supp_info/farmers_markets.html",
  },
  {
    id: "museum-campus-free-day",
    title: "Illinois Resident Museum Free Day",
    description: "Select museums offering free or reduced admission days.",
    category: "museum",
    costType: "free",
    costLabel: "Free / reduced",
    neighborhood: "Museum Campus",
    location: "Participating Chicago Museums",
    startAt: dateAtOffset(5, 10, 0),
    endAt: dateAtOffset(5, 17, 0),
    link: "https://www.choosechicago.com/articles/museums-art/free-museum-days-in-chicago/",
  },
  {
    id: "riverwalk-yoga",
    title: "Riverwalk Morning Yoga",
    description: "Beginner-friendly outdoor yoga session by the river.",
    category: "fitness",
    costType: "low-cost",
    costLabel: "$5 suggested",
    neighborhood: "The Loop",
    location: "Chicago Riverwalk (Franklin St steps)",
    startAt: dateAtOffset(6, 8, 0),
    endAt: dateAtOffset(6, 9, 0),
    link: "https://www.chicagoriverwalk.us/",
  },
  {
    id: "neighborhood-street-fest",
    title: "Neighborhood Street Fest",
    description: "Local food vendors, live sets, and family activities.",
    category: "community",
    costType: "low-cost",
    costLabel: "$10 suggested donation",
    neighborhood: "West Loop",
    location: "Fulton Market District",
    startAt: dateAtOffset(7, 12, 0),
    endAt: dateAtOffset(7, 19, 0),
    link: "https://www.choosechicago.com/articles/festivals-special-events/chicago-festival-event-guide/",
  },
  {
    id: "grant-park-movie-night",
    title: "Grant Park Movie Night",
    description: "Bring-a-blanket outdoor movie screening.",
    category: "community",
    costType: "free",
    costLabel: "Free",
    neighborhood: "The Loop",
    location: "Grant Park",
    startAt: dateAtOffset(9, 20, 0),
    endAt: dateAtOffset(9, 22, 0),
    link: "https://www.chicagoparkdistrict.com/parks-facilities/grant-park",
  },
  {
    id: "millennium-lunch-concert",
    title: "Millennium Park Lunch Concert",
    description: "Midday live music break near work/school.",
    category: "music",
    costType: "free",
    costLabel: "Free",
    neighborhood: "The Loop",
    location: "Millennium Park",
    startAt: dateAtOffset(10, 12, 15),
    endAt: dateAtOffset(10, 13, 0),
    link: "https://www.chicago.gov/city/en/depts/dca/supp_info/millennium_park9.html",
  },
  {
    id: "south-loop-market",
    title: "South Loop Pop-Up Market",
    description: "Budget-friendly local food + handmade goods.",
    category: "market",
    costType: "free",
    costLabel: "Free entry",
    neighborhood: "South Loop",
    location: "Printers Row Plaza",
    startAt: dateAtOffset(11, 11, 0),
    endAt: dateAtOffset(11, 16, 0),
    link: "https://www.choosechicago.com/articles/neighborhoods/chicago-south-loop-neighborhood-guide/",
  },
  {
    id: "lakefront-group-run",
    title: "Lakefront Weekend Group Run",
    description: "Casual pace run club with 3K and 8K options.",
    category: "fitness",
    costType: "free",
    costLabel: "Free",
    neighborhood: "Near Loop",
    location: "Lakefront Trail (Buckingham Fountain meet point)",
    startAt: dateAtOffset(12, 9, 0),
    endAt: dateAtOffset(12, 10, 30),
    link: "https://www.chicagoparkdistrict.com/parks-facilities/lakefront-trail",
  },
  {
    id: "community-art-walk",
    title: "Community Art Walk",
    description: "Guided walk through Loop murals and public art.",
    category: "community",
    costType: "low-cost",
    costLabel: "$8",
    neighborhood: "The Loop",
    location: "Chicago Cultural Center (start)",
    startAt: dateAtOffset(13, 15, 0),
    endAt: dateAtOffset(13, 16, 30),
    link: "https://www.chicago.gov/city/en/depts/dca/supp_info/chicago_culturalcenter.html",
  },
  {
    id: "field-museum-discount-day",
    title: "Field Museum Discount Day",
    description: "Reduced ticket day for Chicago residents.",
    category: "museum",
    costType: "low-cost",
    costLabel: "$10–$15",
    neighborhood: "Museum Campus",
    location: "Field Museum",
    startAt: dateAtOffset(14, 10, 0),
    endAt: dateAtOffset(14, 17, 0),
    link: "https://www.fieldmuseum.org/visit/free-days",
  },
];

export const CHICAGO_EVENTS = [...EVENTS].sort(
  (a, b) => new Date(a.startAt).getTime() - new Date(b.startAt).getTime()
);
